# Generated by Django 5.2.17 on 2026-08-14 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Tables already exist under their historical portal_* names.
            # This migration transfers Django model ownership only.
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='SMSOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='شماره تلفن همراه')),
                ('code', models.CharField(max_length=128, verbose_name='هش کد OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده گردیده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان صدور')),
            ],
            options={
                'verbose_name': 'کد تایید OTP',
                'verbose_name_plural': 'کدهای تایید OTP (ورود پیامکی)',
                'db_table': 'portal_smsotpcode',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سازمان / بیمارستان')),
                ('contact_person', models.CharField(max_length=150, verbose_name='نام رابط اصلی سازمان')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='شماره تماس سازمان')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل سازمان')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس سازمان')),
                ('national_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی / شناسه ملی')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت سازمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات / یادداشت')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس لوگوی سازمان')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='برچسب\u200cها (با کاما جدا کنید)')),
                ('portal_access', models.BooleanField(default=True, verbose_name='دسترسی به پورتال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت سازمان')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اصلی / مالک سازمان')),
            ],
            options={
                'verbose_name': 'سازمان / مشتری',
                'verbose_name_plural': 'سازمان\u200cها و مشتریان',
                'db_table': 'portal_clientorganization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره تلفن همراه')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(choices=[('OWNER', 'مالک سازمان'), ('MEMBER', 'عضو سازمان')], default='MEMBER', max_length=10, verbose_name='نقش دسترسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization', verbose_name='سازمان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_member', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'عضو سازمان',
                'verbose_name_plural': 'اعضای سازمان\u200cها',
                'db_table': 'portal_clientmember',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('national_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان شغلی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس پستی')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره شخص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'db_table': 'portal_userprofile',
            },
        ),
            ],
        ),
    ]
