# Generated by Django 4.2.30 on 2026-08-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سازمان / بیمارستان')),
                ('contact_person', models.CharField(max_length=255, verbose_name='شخص رابط')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('wallet_balance', models.DecimalField(decimal_places=0, default=24500000, max_digits=12, verbose_name='موجودی کیف پول (تومان)')),
                ('sla_days_remaining', models.IntegerField(default=320, verbose_name='روزهای باقی\u200cمانده پشتیبانی SLA')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت حساب فعال')),
            ],
            options={
                'verbose_name': 'حساب مشتری',
                'verbose_name_plural': 'حساب\u200cهای مشتریان',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20, verbose_name='شماره گیرنده')),
                ('text', models.TextField(verbose_name='متن پیامک')),
                ('operator', models.CharField(default='همراه اول', max_length=50, verbose_name='اپراتور')),
                ('cost', models.IntegerField(default=75, verbose_name='هزینه (تومان)')),
                ('status', models.CharField(default='delivered', max_length=50, verbose_name='وضعیت تحویل')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'گزارش پیامک',
                'verbose_name_plural': 'گزارشات پیامک',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='سازمان فرستنده')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع تیکت')),
                ('category', models.CharField(default='پشتیبانی SLA ۲۴/۷', max_length=150, verbose_name='دسته\u200cبندی')),
                ('message', models.TextField(verbose_name='متن پیام کاربر')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='پاسخ مدیریت ارشد')),
                ('status', models.CharField(choices=[('pending', 'منتظر پاسخ'), ('resolved', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='pending', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی SLA',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOPUP', 'شارژ کیف پول'), ('SMS_DEDUCT', 'کسر بابت پیامک'), ('AI_DEDUCT', 'کسر بابت OCR / هوش مصنوعی'), ('TRAFFIC_DEDUCT', 'کسر بابت ترافیک WebRTC')], max_length=30, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('description', models.CharField(max_length=550, verbose_name='شرح تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portal.clientorganization', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
            },
        ),
    ]
