# Generated by Django 5.2.17 on 2026-08-12 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کلید API اختصاصی', max_length=150, verbose_name='عنوان کلید')),
                ('key_type', models.CharField(choices=[('PROJECT', 'کلید اختصاصی پروژه'), ('ACCOUNT', 'کلید کلی حساب سازمانی')], default='PROJECT', max_length=20, verbose_name='نوع کلید')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='کلید API اختصاصی')),
                ('is_active', models.BooleanField(default=True, verbose_name='کلید فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
            ],
            options={
                'verbose_name': 'کلید API اختصاصی',
                'verbose_name_plural': 'مدیریت متمرکز کلیدهای API',
            },
        ),
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سازمان / بیمارستان')),
                ('contact_person', models.CharField(max_length=150, verbose_name='نام رابط اصلی سازمان')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='شماره تماس سازمان')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل سازمان')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس سازمان')),
                ('national_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی / شناسه ملی')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت سازمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات / یادداشت')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس لوگوی سازمان')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='برچسب\u200cها (با کاما جدا کنید)')),
                ('portal_access', models.BooleanField(default=True, verbose_name='دسترسی به پورتال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت سازمان')),
            ],
            options={
                'verbose_name': 'سازمان / مشتری',
                'verbose_name_plural': 'سازمان\u200cها و مشتریان',
            },
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom_plan', models.BooleanField(default=False, verbose_name='پلن اختصاصی')),
                ('custom_plan_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام پلن اختصاصی')),
                ('custom_monthly_price', models.IntegerField(default=0, verbose_name='قیمت ماهانه اختصاصی')),
                ('custom_yearly_price', models.IntegerField(default=0, verbose_name='قیمت سالانه اختصاصی')),
                ('custom_server_cost', models.IntegerField(default=0, verbose_name='هزینه سرور اختصاصی')),
                ('custom_support_cost', models.IntegerField(default=0, verbose_name='هزینه پشتیبانی اختصاصی')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='توضیحات پلن اختصاصی')),
                ('status', models.CharField(choices=[('trialing', 'در دوره تست'), ('active', 'فعال'), ('past_due', 'سررسید شده'), ('canceled', 'لغو شده'), ('expired', 'منقضی شده')], default='trialing', max_length=20, verbose_name='وضعیت اشتراک')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ سررسید / انقضا')),
                ('trial_end', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تست')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تمدید خودکار')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل لغو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'اشتراک مشتری',
                'verbose_name_plural': 'اشتراک\u200cهای مشتریان',
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نوتیفیکیشن')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن',
                'verbose_name_plural': 'نوتیفیکیشن\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('subscription', 'خرید / تمدید اشتراک'), ('wallet_recharge', 'شارژ کیف پول'), ('custom', 'خدمات متفرقه و اختصاصی')], default='custom', max_length=50, verbose_name='نوع فاکتور')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات فاکتور')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('amount', models.IntegerField(verbose_name='مبلغ فاکتور (تومان)')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='مبلغ مالیات بر ارزش افزوده')),
                ('total_amount', models.IntegerField(verbose_name='مبلغ کل پرداخت (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('due_date', models.DateField(verbose_name='مهلت پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورهای مالی',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='شرح کالا / خدمات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد / مقدار')),
                ('unit_price', models.IntegerField(verbose_name='مبلغ واحد (تومان)')),
                ('total_price', models.IntegerField(verbose_name='مبلغ کل ردیف (تومان)')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('payment_method', models.CharField(default='کیف پول', max_length=50, verbose_name='روش پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری تراکنش / درگاه')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
            ],
            options={
                'verbose_name': 'رسید پرداخت',
                'verbose_name_plural': 'رسیدهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام پلن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پلن')),
                ('monthly_price', models.IntegerField(default=0, verbose_name='هزینه ماهانه (تومان)')),
                ('yearly_price', models.IntegerField(default=0, verbose_name='هزینه سالانه (تومان)')),
                ('server_cost', models.IntegerField(default=0, verbose_name='هزینه سرور (تومان)')),
                ('support_cost', models.IntegerField(default=0, verbose_name='هزینه پشتیبانی (تومان)')),
                ('features_list', models.TextField(blank=True, verbose_name='لیست ویژگی\u200cها (با خط جدید جدا شود)')),
                ('trial_days', models.IntegerField(default=0, verbose_name='روزهای تست رایگان')),
                ('min_months', models.IntegerField(default=1, verbose_name='حداقل مدت (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='پلن فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پلن قیمت\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای قیمت\u200cگذاری',
            },
        ),
        migrations.CreateModel(
            name='SLASupportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='پشتیبانی طلایی SLA ۲۴/۷', max_length=150, verbose_name='سطح قرارداد پشتیبانی')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع قرارداد')),
                ('duration_months', models.IntegerField(default=12, verbose_name='مدت قرارداد (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='قرارداد فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سیستم')),
            ],
            options={
                'verbose_name': 'قرارداد پشتیبانی SLA',
                'verbose_name_plural': 'قراردادها و پشتیبانی SLA',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=50, verbose_name='شماره گیرنده')),
                ('text', models.TextField(verbose_name='متن پیامک')),
                ('operator', models.CharField(default='همراه اول', max_length=100, verbose_name='اپراتور')),
                ('cost', models.IntegerField(default=75, verbose_name='هزینه (تومان)')),
                ('status', models.CharField(default='delivered', max_length=50, verbose_name='وضعیت تحویل')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'گزارش پیامک',
                'verbose_name_plural': 'گزارشات ارسال پیامک',
            },
        ),
        migrations.CreateModel(
            name='SMSOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='شماره تلفن همراه')),
                ('code', models.CharField(max_length=10, verbose_name='کد ۵ رقمی OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده گردیده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان صدور')),
            ],
            options={
                'verbose_name': 'کد تایید OTP',
                'verbose_name_plural': 'کدهای تایید OTP (ورود پیامکی)',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='نام ثبت\u200cکننده')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع تیکت پشتیبانی')),
                ('message', models.TextField(verbose_name='متن درخواست')),
                ('status', models.CharField(default='open', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تیکت')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی مشتریان',
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='پشتیبانی', max_length=255, verbose_name='نام فرستنده')),
                ('is_admin', models.BooleanField(default=True, verbose_name='آیا پاسخ از طرف ادمین است؟')),
                ('message', models.TextField(verbose_name='متن پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پاسخ')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('national_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان شغلی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس پستی')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره شخص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=29500000, verbose_name='موجودی حساب کیف پول (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='کیف پول فعال است')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'حساب کیف پول',
                'verbose_name_plural': 'امور مالی و کیف پول سازمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='نوع تراکنش')),
                ('amount', models.IntegerField(verbose_name='مبلغ تراکنش (تومان)')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
            },
        ),
    ]
