# Generated by Django 4.2.30 on 2026-08-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={},
        ),
        migrations.CreateModel(
            name='ClientApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کلید دسترسی اصلی پروژه', max_length=150, verbose_name='عنوان کلید')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='کلید API اختصاصی ANPK (anpk_live_...)')),
                ('is_active', models.BooleanField(default=True, verbose_name='کلید فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='portal.clientorganization', verbose_name='سازمان / مشتری')),
            ],
            options={
                'verbose_name': 'کلید API پروژه مشتری',
                'verbose_name_plural': 'کلیدهای API پروژه\u200cهای مشتریان (ANPK API Keys)',
            },
        ),
    ]
