# Generated by Django 5.2.17 on 2026-08-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='projects.clientcontractproject', verbose_name='پروژه مرتبط (اختیاری)'),
        ),
        migrations.AddField(
            model_name='clientorganization',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اصلی / مالک سازمان'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='portal.clientorganization', verbose_name='سازمان / کاربر مالک کیف پول'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='portal.clientorganization', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='portal.clientsubscription', verbose_name='بابت اشتراک'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.invoice', verbose_name='فاکتور'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.invoice', verbose_name='فاکتور مربوطه'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.pricingplan', verbose_name='پلن انتخابی'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_contracts', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portal.supportticket', verbose_name='تیکت مربوطه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portal.wallet', verbose_name='کیف پول'),
        ),
    ]
