# Generated by Django 4.2.30 on 2026-08-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_projectapikey'),
        ('portal', '0002_alter_supportticket_options_clientapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کلید API اختصاصی', max_length=150, verbose_name='عنوان کلید')),
                ('key_type', models.CharField(choices=[('PROJECT', 'کلید اختصاصی پروژه'), ('ACCOUNT', 'کلید کلی حساب سازمانی')], default='PROJECT', max_length=20, verbose_name='نوع کلید')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='کلید API اختصاصی (anpk_live_...)')),
                ('is_active', models.BooleanField(default=True, verbose_name='کلید فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='portal.clientorganization', verbose_name='سازمان / کاربر مالک کیف پول')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='projects.clientcontractproject', verbose_name='پروژه مرتبط (اختیاری)')),
            ],
            options={
                'verbose_name': 'کلید API اختصاصی',
                'verbose_name_plural': 'مدیریت متمرکز کلیدهای API (ANPK Unified API Keys)',
            },
        ),
        migrations.DeleteModel(
            name='ClientApiKey',
        ),
    ]
