# Generated by Django 4.2.30 on 2026-08-13 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره تلفن همراه')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(choices=[('OWNER', 'مالک سازمان'), ('MEMBER', 'عضو سازمان')], default='MEMBER', max_length=10, verbose_name='نقش دسترسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portal.clientorganization', verbose_name='سازمان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_member', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'عضو سازمان',
                'verbose_name_plural': 'اعضای سازمان\u200cها',
            },
        ),
    ]
