# Generated by Django 4.2.30 on 2026-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_apikey_delete_clientapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تلفن همراه')),
                ('code', models.CharField(max_length=10, verbose_name='کد ۵ رقمی OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده گردیده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان صدور')),
            ],
            options={
                'verbose_name': 'کد تایید OTP',
                'verbose_name_plural': 'مدیریت کدهای تایید OTP (ورود پیامکی)',
            },
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={},
        ),
    ]
