# Generated by Django 4.2.30 on 2026-08-08 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_smsotpcode_alter_apikey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientorganization',
            options={'verbose_name': 'حساب مشتری / سازمان', 'verbose_name_plural': 'مدیریت حساب مشتریان و سازمان\u200cها'},
        ),
        migrations.RemoveField(
            model_name='clientorganization',
            name='is_active',
        ),
        migrations.AddField(
            model_name='clientorganization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='clientorganization',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سیستم جنگو'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='contact_person',
            field=models.CharField(max_length=150, verbose_name='نام رابط اصلی'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام سازمان / مشتری'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='شماره تماس (موبایل لاگین)'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='wallet_balance',
            field=models.IntegerField(default=24500000, verbose_name='موجودی کیف پول (تومان)'),
        ),
    ]
