# Generated by Django 4.2.30 on 2026-08-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_clientorganization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsotpcode',
            options={'verbose_name': 'کد تایید OTP', 'verbose_name_plural': 'کدهای تایید OTP (ورود پیامکی)'},
        ),
    ]
