# Generated by Django 5.2.17 on 2026-08-14 20:56

import django.db.models.deletion
from django.db import migrations, models


def backfill_project_relations(apps, schema_editor):
    Project = apps.get_model('projects', 'ClientContractProject')
    Subscription = apps.get_model('portal', 'ClientSubscription')
    SLA = apps.get_model('portal', 'SLASupportContract')
    Ticket = apps.get_model('portal', 'SupportTicket')
    Invoice = apps.get_model('portal', 'Invoice')

    def primary_project(client_id):
        return Project.objects.filter(client_id=client_id).order_by('-is_active', 'id').first()

    for subscription in Subscription.objects.filter(project__isnull=True):
        project = primary_project(subscription.client_id)
        if project:
            subscription.project_id = project.id
            subscription.save(update_fields=['project'])

    for contract in SLA.objects.filter(project__isnull=True):
        project = primary_project(contract.client_id)
        if not project:
            continue
        contract.project_id = project.id
        subscription = Subscription.objects.filter(
            project_id=project.id,
            sla_contract__isnull=True,
        ).order_by('-start_date', '-id').first()
        if subscription:
            contract.subscription_id = subscription.id
        contract.save(update_fields=['project', 'subscription'])

    for ticket in Ticket.objects.filter(project__isnull=True).exclude(client__isnull=True):
        project = primary_project(ticket.client_id)
        if project:
            ticket.project_id = project.id
            ticket.save(update_fields=['project'])

    for invoice in Invoice.objects.filter(project__isnull=True).exclude(subscription__isnull=True):
        if invoice.subscription.project_id:
            invoice.project_id = invoice.subscription.project_id
            invoice.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_wallet_zero_default'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscription',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='availability_percentage',
            field=models.DecimalField(decimal_places=2, default=99.9, max_digits=5, verbose_name='دسترس\u200cپذیری تضمین\u200cشده (درصد)'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_contracts', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='resolution_time_hours',
            field=models.PositiveIntegerField(default=4, verbose_name='حداکثر زمان رفع خطای بحرانی (ساعت)'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='response_time_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='حداکثر زمان پاسخ اولیه (دقیقه)'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_contract', to='portal.clientsubscription', verbose_name='اشتراک مرتبط'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='support_schedule',
            field=models.CharField(default='24/7', max_length=50, verbose_name='ساعات پشتیبانی'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.RunPython(backfill_project_relations, migrations.RunPython.noop),
    ]
