# Generated by Django 4.2.30 on 2026-08-08 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_alter_smsotpcode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientorganization',
            options={'verbose_name': 'سازمان / مشتری', 'verbose_name_plural': '۱. مدیریت سازمان\u200cها و مشتریان (Organizations)'},
        ),
        migrations.RemoveField(
            model_name='clientorganization',
            name='user',
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='contact_person',
            field=models.CharField(max_length=150, verbose_name='نام رابط اصلی سازمان'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت سازمان'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام سازمان / بیمارستان'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='شماره تماس سازمان'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='wallet_balance',
            field=models.IntegerField(default=24500000, verbose_name='موجودی کیف پول سازمان (تومان)'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره همراه کاربر')),
                ('job_title', models.CharField(default='نماینده سازمان', max_length=150, verbose_name='سمت شغلی')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='portal.clientorganization', verbose_name='سازمان مربوطه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر جنگو')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
    ]
