# Generated by Django 4.2.30 on 2026-08-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0007_alter_clientorganization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorganization',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اصلی / مالک سازمان'),
        ),
    ]
