# Generated by Django 5.2.17 on 2026-08-14 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('portal', '0007_clientsubscription_project_invoice_project_and_more'),
        ('projects', '0002_alter_clientcontractproject_client'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Every relation still targets the same portal_clientorganization
            # table. Only the owning Django app/model changes.
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='clientmember',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='clientmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientorganization',
            name='owner_user',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.organization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.organization', verbose_name='سازمان / کاربر مالک کیف پول'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.organization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='slasupportcontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_contracts', to='accounts.organization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization', verbose_name='سازمان / مشتری'),
        ),
        migrations.DeleteModel(
            name='SMSOTPCode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientMember',
        ),
        migrations.DeleteModel(
            name='ClientOrganization',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
            ],
        ),
    ]
