# Generated by Django 5.2.17 on 2026-08-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('integrations', '0001_initial'),
        ('portal', '0008_remove_clientmember_organization_and_more'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='clientsubscription',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='clientsubscription',
            name='project',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='slasupportcontract',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='inappnotification',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='slasupportcontract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='slasupportcontract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='client',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='client',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
        migrations.DeleteModel(
            name='ClientSubscription',
        ),
        migrations.DeleteModel(
            name='InAppNotification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='SLASupportContract',
        ),
        migrations.DeleteModel(
            name='SMSLog',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
            ],
        ),
    ]
