# Generated by Django 4.2.30 on 2026-08-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_clientorganization_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLASupportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='پشتیبانی طلایی SLA ۲۴/۷', max_length=150, verbose_name='سطح قرارداد پشتیبانی')),
                ('remaining_days', models.IntegerField(default=320, verbose_name='روزهای باقی\u200cمانده پشتیبانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='قرارداد فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عقد قرارداد')),
            ],
            options={
                'verbose_name': 'قرارداد پشتیبانی SLA',
                'verbose_name_plural': '۲. قراردادها و پشتیبانی SLA (SLA Contracts)',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=24500000, verbose_name='موجودی حساب کیف پول (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='کیف پول فعال است')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'حساب کیف پول',
                'verbose_name_plural': '۱. امور مالی و کیف پول سازمان\u200cها (Wallets & Finance)',
            },
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'کلید API اختصاصی', 'verbose_name_plural': '۳. مدیریت متمرکز کلیدهای API (API Keys)'},
        ),
        migrations.AlterModelOptions(
            name='clientorganization',
            options={'verbose_name': 'سازمان / مشتری', 'verbose_name_plural': 'سازمان\u200cها و مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'verbose_name': 'گزارش پیامک', 'verbose_name_plural': 'گزارشات ارسال پیامک'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'تیکت پشتیبانی', 'verbose_name_plural': 'تیکت\u200cهای پشتیبانی مشتریان'},
        ),
        migrations.RemoveField(
            model_name='clientorganization',
            name='sla_days_remaining',
        ),
        migrations.RemoveField(
            model_name='clientorganization',
            name='wallet_balance',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='client',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='operator',
            field=models.CharField(default='همراه اول', max_length=100, verbose_name='اپراتور'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='recipient',
            field=models.CharField(max_length=50, verbose_name='شماره گیرنده'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='نام ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تیکت'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='message',
            field=models.TextField(verbose_name='متن درخواست'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default='open', max_length=50, verbose_name='وضعیت (open, answered, closed)'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='موضوع تیکت پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.IntegerField(verbose_name='مبلغ تراکنش (تومان)'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(max_length=255, verbose_name='توضیحات تراکنش'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(max_length=50, verbose_name='نوع تراکنش (e.g. CHARGE, SMS_DEDUCT, AI_DEDUCT)'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='wallet',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_contract', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portal.wallet', verbose_name='کیف پول'),
        ),
    ]
