# Generated by Django 4.2.30 on 2026-08-08 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_slasupportcontract_wallet_alter_apikey_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slasupportcontract',
            name='remaining_days',
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='duration_months',
            field=models.IntegerField(default=12, verbose_name='مدت قرارداد (ماه)'),
        ),
        migrations.AddField(
            model_name='slasupportcontract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع قرارداد'),
        ),
        migrations.AlterField(
            model_name='slasupportcontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سیستم'),
        ),
    ]
