# Generated by Django 4.2.30 on 2026-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_slasupportcontract_remaining_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'کلید API اختصاصی', 'verbose_name_plural': 'مدیریت متمرکز کلیدهای API'},
        ),
        migrations.AlterModelOptions(
            name='slasupportcontract',
            options={'verbose_name': 'قرارداد پشتیبانی SLA', 'verbose_name_plural': 'قراردادها و پشتیبانی SLA'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'حساب کیف پول', 'verbose_name_plural': 'امور مالی و کیف پول سازمان\u200cها'},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='کلید API اختصاصی'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default='open', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(max_length=50, verbose_name='نوع تراکنش'),
        ),
    ]
