# Generated by Django 4.2.30 on 2026-08-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_apikey_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSOTPCode',
        ),
    ]
