# Generated by Django 4.2.30 on 2026-08-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_clientcontractproject_options_and_more'),
        ('portal', '0012_delete_smsotpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=29500000, verbose_name='موجودی حساب کیف پول (تومان)'),
        ),
    ]
