# Generated by Django 4.2.30 on 2026-08-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_smslog_project_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='شماره تلفن همراه')),
                ('code', models.CharField(max_length=10, verbose_name='کد ۵ رقمی OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده گردیده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان صدور')),
            ],
            options={
                'verbose_name': 'کد تایید OTP',
                'verbose_name_plural': 'کدهای تایید OTP (ورود پیامکی)',
            },
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='phone',
            field=models.CharField(db_index=True, max_length=50, verbose_name='شماره تماس سازمان'),
        ),
        migrations.AlterField(
            model_name='slasupportcontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_contracts', to='portal.clientorganization', verbose_name='سازمان / مشتری'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='recipient',
            field=models.CharField(db_index=True, max_length=50, verbose_name='شماره گیرنده'),
        ),
    ]
