# Generated by Django 4.2.30 on 2026-08-08 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_smsotpcode_alter_clientorganization_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ سررسید / انقضا')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تمدید خودکار')),
                ('is_active', models.BooleanField(default=True, verbose_name='اشتراک فعال است')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='portal.clientorganization', verbose_name='سازمان / مشتری')),
            ],
            options={
                'verbose_name': 'اشتراک مشتری',
                'verbose_name_plural': 'اشتراک\u200cهای مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('amount', models.IntegerField(verbose_name='مبلغ فاکتور (تومان)')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='مبلغ مالیات بر ارزش افزوده')),
                ('total_amount', models.IntegerField(verbose_name='مبلغ کل پرداخت (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('due_date', models.DateField(verbose_name='مهلت پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='portal.clientorganization', verbose_name='مشتری')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='portal.clientsubscription', verbose_name='بابت اشتراک')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورهای مالی',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام پلن')),
                ('monthly_price', models.IntegerField(default=0, verbose_name='هزینه ماهانه (تومان)')),
                ('yearly_price', models.IntegerField(default=0, verbose_name='هزینه سالانه (تومان)')),
                ('features_list', models.TextField(blank=True, verbose_name='لیست ویژگی\u200cها (با خط جدید جدا شود)')),
                ('is_active', models.BooleanField(default=True, verbose_name='پلن فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پلن قیمت\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای قیمت\u200cگذاری',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('payment_method', models.CharField(default='کیف پول', max_length=50, verbose_name='روش پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری تراکنش / درگاه')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.invoice', verbose_name='فاکتور مربوطه')),
            ],
            options={
                'verbose_name': 'رسید پرداخت',
                'verbose_name_plural': 'رسیدهای پرداخت',
            },
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.pricingplan', verbose_name='پلن انتخابی'),
        ),
    ]
