# Generated by Django 4.2.30 on 2026-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_clientsubscription_invoice_pricingplan_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscription',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری تراکنش / درگاه'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات فاکتور'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('subscription', 'خرید / تمدید اشتراک'), ('wallet_recharge', 'شارژ کیف پول'), ('custom', 'خدمات متفرقه و اختصاصی')], default='custom', max_length=50, verbose_name='نوع فاکتور'),
        ),
    ]
