# Generated by Django 4.2.30 on 2026-08-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_clientsubscription_reference_id_invoice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='شرح کالا / خدمات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد / مقدار')),
                ('unit_price', models.IntegerField(verbose_name='مبلغ واحد (تومان)')),
                ('total_price', models.IntegerField(verbose_name='مبلغ کل ردیف (تومان)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
            },
        ),
    ]
