# Generated by Django 4.2.30 on 2026-08-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='پشتیبانی', max_length=255, verbose_name='نام فرستنده')),
                ('is_admin', models.BooleanField(default=True, verbose_name='آیا پاسخ از طرف ادمین است؟')),
                ('message', models.TextField(verbose_name='متن پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پاسخ')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portal.supportticket', verbose_name='تیکت مربوطه')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت',
            },
        ),
    ]
