# Generated by Django 4.2.30 on 2026-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)'),
        ),
    ]
