# Generated by Django 5.2.17 on 2026-08-12 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_subscription_custom_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='clientsubscription',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.pricingplan', verbose_name='پلن انتخابی'),
        ),
    ]
