# Generated by Django 5.2.17 on 2026-08-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا (slug)')),
                ('icon_name', models.CharField(default='Layers', max_length=100, verbose_name='نام آیکون (Lucide)')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات دسته\u200cبندی')),
                ('order', models.IntegerField(default=0, verbose_name='اولویت نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان راهکار تخصصی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا (slug)')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='زیرعنوان / دستاورد شاخص')),
                ('description', models.TextField(verbose_name='توضیحات جامع راهکار و چالش\u200cهای حل\u200cشده')),
                ('icon_name', models.CharField(default='ShieldCheck', max_length=100, verbose_name='نام آیکون (Lucide)')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='تصویر بنر / معماری راهکار')),
                ('target_industries', models.TextField(blank=True, default='', verbose_name='صنایع و مراجع هدف (هرکدام در یک خط)')),
                ('key_benefits', models.TextField(blank=True, default='', verbose_name='مزایای کلیدی راهکار (هرکدام در یک خط)')),
                ('use_cases', models.TextField(blank=True, default='', verbose_name='سناریوهای واقعی استفاده (Use Cases)')),
                ('architecture_summary', models.TextField(blank=True, default='', verbose_name='خلاصه معماری و تکنولوژی\u200cهای به\u200cکاررفته')),
                ('demo_url', models.URLField(blank=True, default='', verbose_name='لینک دمو یا درخواست مشاوره')),
                ('is_featured', models.BooleanField(default=True, verbose_name='نمایش ویژه در صفحه اصلی')),
                ('order', models.IntegerField(default=0, verbose_name='اولویت نمایش')),
            ],
            options={
                'verbose_name': 'راهکار تخصصی',
                'verbose_name_plural': 'راهکارهای تخصصی صنایع & سازمان\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا (slug)')),
                ('short_description', models.TextField(verbose_name='توضیح کوتاه (چکیده کارت)')),
                ('full_description', models.TextField(blank=True, default='', verbose_name='توضیحات جامع و کامل معرفی محصول')),
                ('icon_name', models.CharField(default='Bot', max_length=100, verbose_name='نام آیکون (Lucide)')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس تصویر بنر / اسکرین\u200cشات')),
                ('status', models.CharField(default='دمو فعال / آماده استقرار', max_length=100, verbose_name='وضعیت توسعه و تحویل')),
                ('demo_url', models.URLField(blank=True, default='', verbose_name='لینک آنلاین دمو / سامانه')),
                ('catalog_pdf_url', models.URLField(blank=True, default='', verbose_name='لینک کاتالوگ PDF / دفترچه فنی')),
                ('features_list', models.TextField(blank=True, default='', verbose_name='لیست امکانات و قابلیت\u200cها (هرکدام در یک خط)')),
                ('technical_specs', models.TextField(blank=True, default='', verbose_name='مشخصات فنی و زیرساخت (هرکدام در یک خط)')),
                ('is_featured', models.BooleanField(default=True, verbose_name='نمایش ویژه در صفحه اصلی')),
                ('order', models.IntegerField(default=0, verbose_name='اولویت نمایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory', verbose_name='دسته\u200cبندی محصول')),
            ],
            options={
                'verbose_name': 'محصول نرم\u200cافزاری',
                'verbose_name_plural': 'محصولات نرم\u200cافزاری & کلود',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان قابلیت')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات قابلیت')),
                ('icon_name', models.CharField(default='CheckCircle2', max_length=100, verbose_name='نام آیکون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'قابلیت محصول',
                'verbose_name_plural': 'قابلیت\u200cها و امکانات محصول',
            },
        ),
        migrations.CreateModel(
            name='SolutionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دستاورد / مزیت')),
                ('metric_value', models.CharField(blank=True, default='', max_length=50, verbose_name='مقدار عددی شاخص (e.g. +35%)')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات تکمیلی')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='catalog.solution', verbose_name='راهکار مرتبط')),
            ],
            options={
                'verbose_name': 'مزیت راهکار',
                'verbose_name_plural': 'مزایا و دستاوردهای راهکار',
            },
        ),
    ]
