# Generated by Django 5.2.17 on 2026-08-15 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_organization_owner_user'),
        ('portal', '0008_remove_clientmember_organization_and_more'),
        ('projects', '0002_alter_clientcontractproject_client'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام پلن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پلن')),
                ('monthly_price', models.IntegerField(default=0, verbose_name='هزینه ماهانه (تومان)')),
                ('yearly_price', models.IntegerField(default=0, verbose_name='هزینه سالانه (تومان)')),
                ('server_cost', models.IntegerField(default=0, verbose_name='هزینه سرور (تومان)')),
                ('support_cost', models.IntegerField(default=0, verbose_name='هزینه پشتیبانی (تومان)')),
                ('features_list', models.TextField(blank=True, verbose_name='لیست ویژگی\u200cها (با خط جدید جدا شود)')),
                ('trial_days', models.IntegerField(default=0, verbose_name='روزهای تست رایگان')),
                ('min_months', models.IntegerField(default=1, verbose_name='حداقل مدت (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='پلن فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پلن قیمت\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای قیمت\u200cگذاری',
                'db_table': 'portal_pricingplan',
            },
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom_plan', models.BooleanField(default=False, verbose_name='پلن اختصاصی')),
                ('custom_plan_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام پلن اختصاصی')),
                ('custom_monthly_price', models.IntegerField(default=0, verbose_name='قیمت ماهانه اختصاصی')),
                ('custom_yearly_price', models.IntegerField(default=0, verbose_name='قیمت سالانه اختصاصی')),
                ('custom_server_cost', models.IntegerField(default=0, verbose_name='هزینه سرور اختصاصی')),
                ('custom_support_cost', models.IntegerField(default=0, verbose_name='هزینه پشتیبانی اختصاصی')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='توضیحات پلن اختصاصی')),
                ('status', models.CharField(choices=[('trialing', 'در دوره تست'), ('active', 'فعال'), ('past_due', 'سررسید شده'), ('canceled', 'لغو شده'), ('expired', 'منقضی شده')], default='trialing', max_length=20, verbose_name='وضعیت اشتراک')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ سررسید / انقضا')),
                ('trial_end', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تست')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تمدید خودکار')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل لغو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organization', verbose_name='سازمان / مشتری')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='projects.clientcontractproject', verbose_name='پروژه مرتبط')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.pricingplan', verbose_name='پلن انتخابی')),
            ],
            options={
                'verbose_name': 'اشتراک مشتری',
                'verbose_name_plural': 'اشتراک\u200cهای مشتریان',
                'db_table': 'portal_clientsubscription',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('subscription', 'خرید / تمدید اشتراک'), ('wallet_recharge', 'شارژ کیف پول'), ('custom', 'خدمات متفرقه و اختصاصی')], default='custom', max_length=50, verbose_name='نوع فاکتور')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات فاکتور')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('amount', models.IntegerField(verbose_name='مبلغ فاکتور (تومان)')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='مبلغ مالیات بر ارزش افزوده')),
                ('total_amount', models.IntegerField(verbose_name='مبلغ کل پرداخت (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('due_date', models.DateField(verbose_name='مهلت پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization', verbose_name='مشتری')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.clientcontractproject', verbose_name='پروژه مرتبط')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.clientsubscription', verbose_name='بابت اشتراک')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورهای مالی',
                'db_table': 'portal_invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='شرح کالا / خدمات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد / مقدار')),
                ('unit_price', models.IntegerField(verbose_name='مبلغ واحد (تومان)')),
                ('total_price', models.IntegerField(verbose_name='مبلغ کل ردیف (تومان)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
                'db_table': 'portal_invoiceitem',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('payment_method', models.CharField(default='کیف پول', max_length=50, verbose_name='روش پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری تراکنش / درگاه')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice', verbose_name='فاکتور مربوطه')),
            ],
            options={
                'verbose_name': 'رسید پرداخت',
                'verbose_name_plural': 'رسیدهای پرداخت',
                'db_table': 'portal_payment',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='موجودی حساب کیف پول (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='کیف پول فعال است')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.organization', verbose_name='سازمان / مشتری')),
            ],
            options={
                'verbose_name': 'حساب کیف پول',
                'verbose_name_plural': 'کیف پول سازمان\u200cها',
                'db_table': 'portal_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='نوع تراکنش')),
                ('amount', models.IntegerField(verbose_name='مبلغ تراکنش (تومان)')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'db_table': 'portal_wallettransaction',
            },
        ),
            ],
        ),
    ]
