# Generated by Django 5.2.17 on 2026-08-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='clientsubscription',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='clientsubscription',
            name='project',
        ),
            ],
        ),
    ]
