# Generated by Django 5.2.17 on 2026-08-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_clientsubscription_client_and_more'),
        ('subscriptions', '0001_initial'),
        ('support', '0002_alter_slasupportcontract_subscription'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.clientsubscription', verbose_name='بابت اشتراک'),
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
        migrations.DeleteModel(
            name='ClientSubscription',
        ),
            ],
        ),
    ]
