# Generated by Django 5.2.17 on 2026-08-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_subscription_delete_pricingplan_and_more'),
        ('projects', '0002_alter_clientcontractproject_client'),
        ('subscriptions', '0002_move_billing_content_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول سازمان\u200cها'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تسویه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='کلید یکتایی عملیات'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('SUCCESS', 'موفق'), ('REFUNDED', 'برگشت\u200cخورده')], default='SUCCESS', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='موجودی بعد'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='موجودی قبل'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True, verbose_name='کلید یکتایی عملیات'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='billing.invoice', verbose_name='فاکتور مرتبط'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('FINAL', 'قطعی'), ('REVERSED', 'برگشت\u200cخورده')], default='FINAL', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('subscription', 'خرید / تمدید سرویس'), ('wallet_recharge', 'شارژ کیف پول'), ('custom', 'خدمات متفرقه و اختصاصی')], default='custom', max_length=50, verbose_name='نوع فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.clientsubscription', verbose_name='قرارداد سرویس مرتبط'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.IntegerField(default=0, verbose_name='مالیات (تومان)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(verbose_name='مبلغ نهایی (تومان)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('GATEWAY', 'درگاه پرداخت'), ('WALLET', 'کیف پول'), ('BANK', 'کارت / حواله بانکی')], default='GATEWAY', max_length=50, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=180, null=True, verbose_name='کد پیگیری تراکنش / درگاه'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='موجودی کیف پول (تومان)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
