# Generated by Django 4.2.30 on 2026-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه')),
                ('client_organization', models.CharField(max_length=255, verbose_name='سازمان / بیمارستان طرف قرارداد')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('sprint_progress', models.IntegerField(default=85, verbose_name='درصد پیشرفت اسپرینت جاری')),
                ('active_phase', models.CharField(default='فاز ۳: استقرار بومی', max_length=150, verbose_name='فاز فعال')),
                ('login_url', models.URLField(blank=True, null=True, verbose_name='آدرس ورود به سامانه مستقرشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='پروژه فعال')),
            ],
            options={
                'verbose_name': 'پروژه قراردادی',
                'verbose_name_plural': 'پروژه\u200cها و استقرارها',
            },
        ),
    ]
