# Generated by Django 5.2.17 on 2026-08-12 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پروژه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تکنولوژی')),
                ('category', models.CharField(default='بک\u200cاند', max_length=100, verbose_name='حوزه تکنولوژی')),
            ],
            options={
                'verbose_name': 'تکنولوژی',
                'verbose_name_plural': 'تکنولوژی\u200cهای نرم\u200cافزاری',
            },
        ),
        migrations.CreateModel(
            name='ClientContractProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه قراردادی مشتری')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('contract_number', models.CharField(default='ANPK-CNT-1404-892', max_length=100, verbose_name='شماره رسمی قرارداد')),
                ('contract_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ عقد قرارداد')),
                ('contract_value', models.IntegerField(default=150000000, verbose_name='مبلغ مالی قرارداد (تومان)')),
                ('sprint_progress', models.IntegerField(default=85, verbose_name='درصد پیشرفت کلی اسپرینت')),
                ('active_phase_title', models.CharField(default='فاز ۳: استقرار بومی & مانیتورینگ موتورخانه', max_length=150, verbose_name='عنوان فاز جاری')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل فاز جاری / نهایی')),
                ('login_url', models.URLField(blank=True, null=True, verbose_name='آدرس اختصاصی ورود مشتری به سامانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='پروژه فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_projects', to='portal.clientorganization', verbose_name='سازمان / کاربر مالک پروژه')),
            ],
            options={
                'verbose_name': 'پروژه قراردادی مشتری',
                'verbose_name_plural': 'پروژه\u200cهای خصوصی پورتال مشتریان',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField(default=1, verbose_name='شماره فاز')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فاز اجرایی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات و خروجی\u200cهای این فاز')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='درصد پیشرفت این فاز (۰ تا ۱۰۰)')),
                ('status', models.CharField(choices=[('COMPLETED', 'تکمیل شده (۱۰۰٪)'), ('IN_PROGRESS', 'در حال انجام'), ('PENDING', 'در انتظار شروع')], default='IN_PROGRESS', max_length=20, verbose_name='وضعیت فاز')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع فاز')),
                ('target_delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل تخمینی فاز')),
                ('deliverable_file', models.FileField(blank=True, null=True, upload_to='deliverables/', verbose_name='فایل خروجی (تحویلی)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.clientcontractproject', verbose_name='پروژه مربوطه')),
            ],
            options={
                'verbose_name': 'فاز اجرایی پروژه',
                'verbose_name_plural': 'فازهای اجرایی پروژه',
                'ordering': ['phase_number'],
            },
        ),
        migrations.CreateModel(
            name='PublicPortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه / نمونه\u200cکار')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('client_name_display', models.CharField(max_length=255, verbose_name='نام سازمان / کارفرما')),
                ('summary', models.TextField(verbose_name='خلاصه دستاوردها و ارزش افزوده')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='شرح کامل معماری فنی و جزئیات استقرار')),
                ('sprint_progress', models.IntegerField(default=100, verbose_name='درصد پیشرفت استقرار (۱۰۰٪ کامل)')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='آدرس لینک دمو یا وب\u200cسایت پروژه')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس تصویر نمونه\u200cکار')),
                ('is_featured', models.BooleanField(default=True, verbose_name='نمایش در نمونه\u200cکارهای ویژه صفحه اصلی')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='عنوان سئو (Meta Title)')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات سئو (Meta Description)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در پورتفولیو')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory', verbose_name='دسته\u200cبندی اصلی پروژه')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology', verbose_name='تکنولوژی\u200cهای استفاده\u200cشده')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار عمومی',
                'verbose_name_plural': 'پروژه\u200cها و نمونه\u200cکارهای عمومی سایت',
            },
        ),
    ]
