# Generated by Django 4.2.30 on 2026-08-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_supportticket_options_clientapikey'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='portal.clientorganization', verbose_name='سازمان / کاربر مالک پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_organization',
            field=models.CharField(max_length=255, verbose_name='نام نمایش سازمان طرف قرارداد'),
        ),
        migrations.CreateModel(
            name='ProjectApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کلید API ماژول پروژه', max_length=150, verbose_name='عنوان کلید API پروژه')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='کلید API اختصاصی پروژه (anpk_proj_...)')),
                ('is_active', models.BooleanField(default=True, verbose_name='کلید فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_api_keys', to='projects.project', verbose_name='پروژه مربوطه')),
            ],
            options={
                'verbose_name': 'کلید API اختصاصی پروژه',
                'verbose_name_plural': 'کلیدهای API پروژه\u200cها (Project API Keys)',
            },
        ),
    ]
