# Generated by Django 4.2.30 on 2026-08-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_supportticket_options_clientapikey'),
        ('projects', '0002_project_client_alter_project_client_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نمونه\u200cکار / استقرار عمومی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا (slug)')),
                ('category', models.CharField(max_length=150, verbose_name='دسته\u200cبندی (e.g. سلامت دیجیتال، CMMS، WebRTC)')),
                ('client_name_display', models.CharField(max_length=255, verbose_name='نام سازمان / مشتری (جهت نمایش عمومی)')),
                ('summary', models.TextField(verbose_name='خلاصه توضیحات رزومه')),
                ('technologies_used', models.CharField(default='Microservices, Django, WebRTC, Python, React', max_length=500, verbose_name='تکنولوژی\u200cهای استفاده\u200cشده')),
                ('is_featured', models.BooleanField(default=True, verbose_name='نمایش در نمونه\u200cکارهای ویژه صفحه اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار عمومی (پورتفولیو سایت)',
                'verbose_name_plural': '۱. پروژه\u200cها و نمونه\u200cکارهای عمومی سایت (Public Portfolio)',
            },
        ),
        migrations.AlterModelOptions(
            name='projectapikey',
            options={'verbose_name': 'کلید API اختصاصی پروژه', 'verbose_name_plural': '۳. کلیدهای API پروژه\u200cهای مشتریان (Project API Keys)'},
        ),
        migrations.CreateModel(
            name='ClientContractProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه قراردادی مشتری')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('sprint_progress', models.IntegerField(default=85, verbose_name='درصد پیشرفت اسپرینت جاری')),
                ('active_phase', models.CharField(default='فاز ۳: استقرار بومی', max_length=150, verbose_name='فاز فعال')),
                ('login_url', models.URLField(blank=True, null=True, verbose_name='آدرس اختصاصی ورود مشتری به سامانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='پروژه فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عقد قرارداد')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_projects', to='portal.clientorganization', verbose_name='سازمان / کاربر مالک پروژه')),
            ],
            options={
                'verbose_name': 'پروژه قراردادی مشتری',
                'verbose_name_plural': '۲. پروژه\u200cهای خصوصی پورتال مشتریان (Client Projects)',
            },
        ),
        migrations.AlterField(
            model_name='projectapikey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_api_keys', to='projects.clientcontractproject', verbose_name='پروژه قراردادی مربوطه'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
