# Generated by Django 4.2.30 on 2026-08-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_publicportfolioproject_alter_projectapikey_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectApiKey',
        ),
    ]
