# Generated by Django 4.2.30 on 2026-08-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_projectapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicportfolioproject',
            name='demo_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس لینک دمو یا وب\u200cسایت پروژه'),
        ),
        migrations.AddField(
            model_name='publicportfolioproject',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='شرح کامل معماری فنی و جزئیات استقرار'),
        ),
        migrations.AddField(
            model_name='publicportfolioproject',
            name='sprint_progress',
            field=models.IntegerField(default=100, verbose_name='درصد پیشرفت استقرار (۱۰۰٪ کامل)'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='category',
            field=models.CharField(max_length=150, verbose_name='دسته\u200cبندی (e.g. نگه\u200cداشت تأسیسات، WebRTC، سلامت دیجیتال)'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='client_name_display',
            field=models.CharField(max_length=255, verbose_name='نام سازمان / کارفرما (جهت نمایش عمومی)'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در پورتفولیو'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='summary',
            field=models.TextField(verbose_name='خلاصه دستاوردها و ارزش افزوده'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='technologies_used',
            field=models.CharField(default='Python, Django REST, Next.js, PostgreSQL, Docker', max_length=500, verbose_name='تکنولوژی\u200cهای استفاده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان پروژه / نمونه\u200cکار'),
        ),
    ]
