# Generated by Django 4.2.30 on 2026-08-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_publicportfolioproject_demo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا (slug)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پروژه',
                'verbose_name_plural': '۱. مدیریت دسته\u200cبندی\u200cهای پروژه\u200cها (Categories)',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تکنولوژی (e.g. Django, Next.js, WebRTC)')),
                ('category', models.CharField(default='Backend', max_length=100, verbose_name='حوزه تکنولوژی (Backend, Frontend, DevOps, AI)')),
            ],
            options={
                'verbose_name': 'تکنولوژی',
                'verbose_name_plural': '۲. مدیریت تکنولوژی\u200cها (Technologies)',
            },
        ),
        migrations.AlterModelOptions(
            name='clientcontractproject',
            options={'verbose_name': 'پروژه قراردادی مشتری', 'verbose_name_plural': '۴. پروژه\u200cهای خصوصی پورتال مشتریان (Client Projects)'},
        ),
        migrations.AlterModelOptions(
            name='publicportfolioproject',
            options={'verbose_name': 'نمونه\u200cکار عمومی (پورتفولیو سایت)', 'verbose_name_plural': '۳. پروژه\u200cها و نمونه\u200cکارهای عمومی سایت (Public Portfolio)'},
        ),
        migrations.RemoveField(
            model_name='publicportfolioproject',
            name='technologies_used',
        ),
        migrations.AddField(
            model_name='publicportfolioproject',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technology', verbose_name='تکنولوژی\u200cهای استفاده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory', verbose_name='دسته\u200cبندی اصلی پروژه'),
        ),
    ]
