# Generated by Django 4.2.30 on 2026-08-08 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectcategory_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontractproject',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ عقد قرارداد'),
        ),
        migrations.AddField(
            model_name='clientcontractproject',
            name='contract_number',
            field=models.CharField(default='ANPK-CNT-1404-892', max_length=100, verbose_name='شماره رسمی قرارداد'),
        ),
        migrations.AddField(
            model_name='clientcontractproject',
            name='contract_value',
            field=models.IntegerField(default=150000000, verbose_name='مبلغ مالی قرارداد (تومان)'),
        ),
        migrations.AddField(
            model_name='clientcontractproject',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل فاز جاری / نهایی'),
        ),
        migrations.AlterField(
            model_name='clientcontractproject',
            name='active_phase',
            field=models.CharField(default='فاز ۳: استقرار بومی & مانیتورینگ موتورخانه', max_length=150, verbose_name='فاز فعال پروژه'),
        ),
        migrations.AlterField(
            model_name='clientcontractproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم'),
        ),
    ]
