# Generated by Django 4.2.30 on 2026-08-08 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_clientcontractproject_contract_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontractproject',
            name='active_phase',
        ),
        migrations.AddField(
            model_name='clientcontractproject',
            name='active_phase_title',
            field=models.CharField(default='فاز ۳: استقرار بومی & مانیتورینگ موتورخانه', max_length=150, verbose_name='عنوان فاز جاری'),
        ),
        migrations.AlterField(
            model_name='clientcontractproject',
            name='sprint_progress',
            field=models.IntegerField(default=85, verbose_name='درصد پیشرفت کلی اسپرینت'),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField(default=1, verbose_name='شماره فاز (e.g. 1, 2, 3)')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فاز اجرایی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات و خروجی\u200cهای این فاز')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='درصد پیشرفت این فاز (۰ تا ۱۰۰)')),
                ('status', models.CharField(choices=[('COMPLETED', 'تکمیل شده (۱۰۰٪)'), ('IN_PROGRESS', 'در حال انجام'), ('PENDING', 'در انتظار شروع')], default='IN_PROGRESS', max_length=20, verbose_name='وضعیت فاز')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع فاز')),
                ('target_delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل تخمینی فاز')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.clientcontractproject', verbose_name='پروژه مربوطه')),
            ],
            options={
                'verbose_name': 'فاز اجرایی پروژه',
                'verbose_name_plural': 'فازهای کامل پروژه (Project Phases / Roadmap)',
                'ordering': ['phase_number'],
            },
        ),
    ]
