# Generated by Django 4.2.30 on 2026-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_clientcontractproject_active_phase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontractproject',
            options={'verbose_name': 'پروژه قراردادی مشتری', 'verbose_name_plural': 'پروژه\u200cهای خصوصی پورتال مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'دسته\u200cبندی پروژه', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ['phase_number'], 'verbose_name': 'فاز اجرایی پروژه', 'verbose_name_plural': 'فازهای اجرایی پروژه'},
        ),
        migrations.AlterModelOptions(
            name='publicportfolioproject',
            options={'verbose_name': 'نمونه\u200cکار عمومی', 'verbose_name_plural': 'پروژه\u200cها و نمونه\u200cکارهای عمومی سایت'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'تکنولوژی', 'verbose_name_plural': 'تکنولوژی\u200cهای نرم\u200cافزاری'},
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase_number',
            field=models.IntegerField(default=1, verbose_name='شماره فاز'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='client_name_display',
            field=models.CharField(max_length=255, verbose_name='نام سازمان / کارفرما'),
        ),
        migrations.AlterField(
            model_name='publicportfolioproject',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(default='بک\u200cاند', max_length=100, verbose_name='حوزه تکنولوژی'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام تکنولوژی'),
        ),
    ]
