# Generated by Django 4.2.30 on 2026-08-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_clientcontractproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='deliverable_file',
            field=models.FileField(blank=True, null=True, upload_to='deliverables/', verbose_name='فایل خروجی (تحویلی)'),
        ),
    ]
