# Generated by Django 4.2.30 on 2026-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectphase_deliverable_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicportfolioproject',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات سئو (Meta Description)'),
        ),
        migrations.AddField(
            model_name='publicportfolioproject',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='عنوان سئو (Meta Title)'),
        ),
    ]
