# Generated by Django 5.2.17 on 2026-08-15 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_organization_owner_user'),
        ('billing', '0001_initial'),
        ('portal', '0011_remove_stale_portal_content_types'),
        ('projects', '0002_alter_clientcontractproject_client'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام پلن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پلن')),
                ('monthly_price', models.IntegerField(default=0, verbose_name='هزینه ماهانه (تومان)')),
                ('yearly_price', models.IntegerField(default=0, verbose_name='هزینه سالانه (تومان)')),
                ('server_cost', models.IntegerField(default=0, verbose_name='هزینه سرور (تومان)')),
                ('support_cost', models.IntegerField(default=0, verbose_name='هزینه پشتیبانی (تومان)')),
                ('features_list', models.TextField(blank=True, verbose_name='لیست ویژگی\u200cها (با خط جدید جدا شود)')),
                ('trial_days', models.IntegerField(default=0, verbose_name='روزهای تست رایگان')),
                ('min_months', models.IntegerField(default=1, verbose_name='حداقل مدت (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='پلن فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پلن قیمت\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای قیمت\u200cگذاری',
                'db_table': 'portal_pricingplan',
            },
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom_plan', models.BooleanField(default=False, verbose_name='پلن اختصاصی')),
                ('custom_plan_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام پلن اختصاصی')),
                ('custom_monthly_price', models.IntegerField(default=0, verbose_name='قیمت ماهانه اختصاصی')),
                ('custom_yearly_price', models.IntegerField(default=0, verbose_name='قیمت سالانه اختصاصی')),
                ('custom_server_cost', models.IntegerField(default=0, verbose_name='هزینه سرور اختصاصی')),
                ('custom_support_cost', models.IntegerField(default=0, verbose_name='هزینه پشتیبانی اختصاصی')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='توضیحات پلن اختصاصی')),
                ('status', models.CharField(choices=[('trialing', 'در دوره تست'), ('active', 'فعال'), ('past_due', 'سررسید شده'), ('canceled', 'لغو شده'), ('expired', 'منقضی شده')], default='trialing', max_length=20, verbose_name='وضعیت اشتراک')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ سررسید / انقضا')),
                ('trial_end', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تست')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تمدید خودکار')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل لغو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organization', verbose_name='سازمان / مشتری')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='projects.clientcontractproject', verbose_name='پروژه مرتبط')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.pricingplan', verbose_name='پلن انتخابی')),
            ],
            options={
                'verbose_name': 'اشتراک مشتری',
                'verbose_name_plural': 'اشتراک\u200cهای مشتریان',
                'db_table': 'portal_clientsubscription',
            },
        ),
            ],
        ),
    ]
