# Generated by Django 5.2.17 on 2026-08-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_organization_owner_user'),
        ('billing', '0004_alter_wallet_options_invoice_paid_at_and_more'),
        ('projects', '0002_alter_clientcontractproject_client'),
        ('subscriptions', '0002_move_billing_content_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='معتبر از')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='معتبر تا')),
                ('monthly_price', models.PositiveBigIntegerField(verbose_name='قیمت ماهانه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نسخه قیمت پلن',
                'verbose_name_plural': 'نسخه\u200cهای قیمت پلن\u200cها',
                'db_table': 'subscriptions_pricingplanversion',
                'ordering': ('-effective_from', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField(verbose_name='تعداد ماه')),
                ('start_date', models.DateField(verbose_name='شروع دوره')),
                ('end_date', models.DateField(verbose_name='پایان دوره (غیرشامل)')),
                ('monthly_unit_price', models.PositiveBigIntegerField(verbose_name='قیمت ماهانه ثبت\u200cشده')),
                ('subtotal', models.PositiveBigIntegerField(verbose_name='جمع قبل از تخفیف')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف')),
                ('tax_amount', models.PositiveBigIntegerField(default=0, verbose_name='مالیات')),
                ('total_amount', models.PositiveBigIntegerField(verbose_name='مبلغ نهایی')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('INVOICED', 'در انتظار پرداخت'), ('ACTIVE', 'فعال'), ('CANCELED', 'لغوشده'), ('REFUNDED', 'برگشت\u200cخورده')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان فعال\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دوره تمدید سرویس',
                'verbose_name_plural': 'دوره\u200cهای تمدید سرویس',
                'db_table': 'subscriptions_subscriptionperiod',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='clientsubscription',
            options={'verbose_name': 'قرارداد سرویس پروژه', 'verbose_name_plural': 'قراردادهای سرویس پروژه\u200cها'},
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='service_type',
            field=models.CharField(choices=[('HOSTING', 'میزبانی و سرور'), ('SUPPORT', 'پشتیبانی'), ('MAINTENANCE', 'نگهداری دوره\u200cای'), ('OTHER', 'سایر خدمات')], default='SUPPORT', max_length=20, verbose_name='نوع سرویس'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='service_type',
            field=models.CharField(choices=[('HOSTING', 'میزبانی و سرور'), ('SUPPORT', 'پشتیبانی'), ('MAINTENANCE', 'نگهداری دوره\u200cای'), ('OTHER', 'سایر خدمات')], default='SUPPORT', max_length=20, verbose_name='نوع سرویس'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'دوره آزمایشی'), ('active', 'فعال'), ('past_due', 'سررسیدشده'), ('canceled', 'لغوشده'), ('expired', 'منقضی')], default='trialing', max_length=20, verbose_name='وضعیت قرارداد سرویس'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='trial_end',
            field=models.DateField(blank=True, null=True, verbose_name='پایان دوره آزمایشی'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='features_list',
            field=models.TextField(blank=True, verbose_name='فهرست ویژگی\u200cها'),
        ),
        migrations.AddConstraint(
            model_name='clientsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('trialing', 'active', 'past_due'))), fields=('project', 'service_type'), name='unique_open_project_service_agreement'),
        ),
        migrations.AddField(
            model_name='pricingplanversion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_versions', to='subscriptions.pricingplan', verbose_name='پلن'),
        ),
        migrations.AddField(
            model_name='subscriptionperiod',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_period', to='billing.invoice', verbose_name='فاکتور'),
        ),
        migrations.AddField(
            model_name='subscriptionperiod',
            name='price_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='subscriptions.pricingplanversion', verbose_name='نسخه قیمت'),
        ),
        migrations.AddField(
            model_name='subscriptionperiod',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='subscriptions.clientsubscription', verbose_name='قرارداد سرویس'),
        ),
        migrations.AddConstraint(
            model_name='pricingplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'effective_from'), name='unique_plan_price_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='pricingplanversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='price_version_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('months__gt', 0)), name='subscription_period_positive_months'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='subscription_period_valid_range'),
        ),
    ]
