# Generated by Django 5.2.17 on 2026-08-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_organization_owner_user'),
        ('portal', '0008_remove_clientmember_organization_and_more'),
        ('projects', '0002_alter_clientcontractproject_client'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کلید API اختصاصی', max_length=150, verbose_name='عنوان کلید')),
                ('key_type', models.CharField(choices=[('PROJECT', 'کلید اختصاصی پروژه'), ('ACCOUNT', 'کلید کلی حساب سازمانی')], default='PROJECT', max_length=20, verbose_name='نوع کلید')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='کلید API اختصاصی')),
                ('is_active', models.BooleanField(default=True, verbose_name='کلید فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.organization', verbose_name='سازمان / کاربر مالک کیف پول')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='projects.clientcontractproject', verbose_name='پروژه مرتبط (اختیاری)')),
            ],
            options={
                'verbose_name': 'کلید API اختصاصی',
                'verbose_name_plural': 'مدیریت متمرکز کلیدهای API',
                'db_table': 'portal_apikey',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=50, verbose_name='شماره گیرنده')),
                ('text', models.TextField(verbose_name='متن پیامک')),
                ('operator', models.CharField(default='همراه اول', max_length=100, verbose_name='اپراتور')),
                ('cost', models.IntegerField(default=75, verbose_name='هزینه (تومان)')),
                ('status', models.CharField(default='delivered', max_length=50, verbose_name='وضعیت تحویل')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='projects.clientcontractproject', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'گزارش پیامک',
                'verbose_name_plural': 'گزارش\u200cهای ارسال پیامک',
                'db_table': 'portal_smslog',
            },
        ),
            ],
        ),
    ]
