# Generated by Django 4.2.30 on 2026-08-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='متن پرامپت یا تصویر OCR')),
                ('response_text', models.TextField(verbose_name='پاسخ هوش مصنوعی OpenRouter')),
                ('model_used', models.CharField(default='google/gemini-flash-1.5', max_length=150, verbose_name='مدل استفاده\u200cشده')),
                ('tokens_used', models.IntegerField(default=150, verbose_name='توکن مصرفی')),
                ('cost_deducted', models.IntegerField(default=240, verbose_name='مبلغ کسر شده (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان فراخوانی')),
            ],
            options={
                'verbose_name': 'گزارش فراخوانی AI',
                'verbose_name_plural': 'گزارشات هوش مصنوعی & OpenRouter',
            },
        ),
        migrations.CreateModel(
            name='OpenRouterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تنظیمات سرویس OpenRouter AI', max_length=150, verbose_name='عنوان سرویس')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید API OpenRouter (sk-or-v1-...)')),
                ('default_model', models.CharField(default='google/gemini-flash-1.5', max_length=150, verbose_name='مدل پیش\u200cفرض OpenRouter (e.g. google/gemini-2.0-flash, openai/gpt-4o-mini)')),
                ('wallet_rate_per_query', models.IntegerField(default=240, verbose_name='تعرفه کسر از کیف پول بابت هر پرامپت (تومان)')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='حداکثر توکن پاسخ')),
                ('total_queries_count', models.IntegerField(default=1420, verbose_name='مجموع درخواست\u200cهای پردازش شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='سرویس فعال است')),
            ],
            options={
                'verbose_name': 'تنظیمات OpenRouter AI',
                'verbose_name_plural': 'تنظیمات هوش مصنوعی & OpenRouter API',
            },
        ),
        migrations.CreateModel(
            name='SMSGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تنظیمات درگاه پیامک سازمانی', max_length=150, verbose_name='عنوان درگاه')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید API پنل پیامک')),
                ('sender_line', models.CharField(default='1000890412', max_length=50, verbose_name='شماره خط خدماتی فرستنده')),
                ('cost_per_sms', models.IntegerField(default=75, verbose_name='تعرفه کسر از کیف پول هر پیامک (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='خط پیامک فعال است')),
            ],
            options={
                'verbose_name': 'تنظیمات API پیامک',
                'verbose_name_plural': 'تنظیمات سرویس پیامک & API',
            },
        ),
    ]
