# Generated by Django 5.2.17 on 2026-08-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRouterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://openrouter.ai/api/v1/chat/completions', verbose_name='آدرس API پرووایدر هوش مصنوعی')),
                ('api_key', models.CharField(default='sk-or-v1-demo-key-anpk', max_length=255, verbose_name='کلید API سرویس هوش مصنوعی')),
                ('default_model', models.CharField(default='google/gemini-2.5-flash', max_length=150, verbose_name='مدل هوش مصنوعی پیش\u200cفرض')),
                ('wallet_rate_per_query', models.IntegerField(default=240, verbose_name='تعرفه کسر از کیف پول برای هر کوئری (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='سرویس فعال است')),
            ],
            options={
                'verbose_name': 'تنظیمات سرویس هوش مصنوعی',
                'verbose_name_plural': 'تنظیمات هوش مصنوعی و سرویس API',
            },
        ),
        migrations.CreateModel(
            name='SMSGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='کاوه نگار / ملی پیامک واسط', max_length=100, verbose_name='نام سامانه پیامکی')),
                ('api_key', models.CharField(default='sms-gateway-demo-key-anpk', max_length=255, verbose_name='کلید API درگاه پیامک')),
                ('sender_line', models.CharField(default='30005050', max_length=50, verbose_name='خط اختصاصی ارسال پیامک')),
                ('is_active', models.BooleanField(default=True, verbose_name='درگاه فعال است')),
            ],
            options={
                'verbose_name': 'تنظیمات درگاه پیامک',
                'verbose_name_plural': 'تنظیمات سرویس پیامک',
            },
        ),
        migrations.CreateModel(
            name='SystemNodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام نود / سرویس کلود')),
                ('status_label', models.CharField(default='آنلاین', max_length=50, verbose_name='وضعیت پایش (e.g. آنلاین، نگه\u200cداشت)')),
                ('uptime_percentage', models.CharField(default='۹۹.۹٪', max_length=20, verbose_name='درصد پایداری (Uptime)')),
                ('latency_ms', models.IntegerField(default=25, verbose_name='تخمین تاخیر شبکه (ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نود فعال است')),
            ],
            options={
                'verbose_name': 'نود کلود و وضعیت پایداری',
                'verbose_name_plural': 'پایش آنلاین نودها و سرویس\u200cها (Node Status)',
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(default='', verbose_name='سوال / پرامپت کاربر')),
                ('ai_response', models.TextField(default='', verbose_name='پاسخ هوش مصنوعی')),
                ('model_used', models.CharField(max_length=150, verbose_name='مدل استفاده\u200cشده')),
                ('cost_deducted', models.IntegerField(default=240, verbose_name='هزینه کسرشده از کیف پول (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ کوئری')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='projects.clientcontractproject', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'لاگ پردازش هوش مصنوعی',
                'verbose_name_plural': 'گزارشات پردازش هوش مصنوعی',
            },
        ),
    ]
