# Generated by Django 4.2.30 on 2026-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrouterconfig',
            name='api_url',
            field=models.CharField(default='https://openrouter.ai/api/v1/chat/completions', max_length=500, verbose_name='آدرس کامل API پرووایدر (e.g. OpenRouter, Local Ollama, DeepSeek, OpenAI)'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید API (sk-...)'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='default_model',
            field=models.CharField(default='google/gemini-flash-1.5', max_length=150, verbose_name='مدل پیش\u200cفرض AI (e.g. google/gemini-2.0-flash, deepseek-chat, gpt-4o-mini)'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='title',
            field=models.CharField(default='تنظیمات سرویس هوش مصنوعی (OpenRouter / Custom AI API)', max_length=150, verbose_name='عنوان سرویس'),
        ),
    ]
