# Generated by Django 4.2.30 on 2026-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_openrouterconfig_api_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ailog',
            options={'verbose_name': 'لاگ پردازش هوش مصنوعی', 'verbose_name_plural': 'گزارشات پردازش هوش مصنوعی'},
        ),
        migrations.AlterModelOptions(
            name='openrouterconfig',
            options={'verbose_name': 'تنظیمات سرویس هوش مصنوعی', 'verbose_name_plural': 'تنظیمات هوش مصنوعی و سرویس API'},
        ),
        migrations.AlterModelOptions(
            name='smsgatewayconfig',
            options={'verbose_name': 'تنظیمات درگاه پیامک', 'verbose_name_plural': 'تنظیمات سرویس پیامک'},
        ),
        migrations.RemoveField(
            model_name='ailog',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='ailog',
            name='response_text',
        ),
        migrations.RemoveField(
            model_name='ailog',
            name='tokens_used',
        ),
        migrations.RemoveField(
            model_name='openrouterconfig',
            name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='openrouterconfig',
            name='title',
        ),
        migrations.RemoveField(
            model_name='openrouterconfig',
            name='total_queries_count',
        ),
        migrations.RemoveField(
            model_name='smsgatewayconfig',
            name='cost_per_sms',
        ),
        migrations.RemoveField(
            model_name='smsgatewayconfig',
            name='title',
        ),
        migrations.AddField(
            model_name='ailog',
            name='ai_response',
            field=models.TextField(default='', verbose_name='پاسخ هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='ailog',
            name='user_query',
            field=models.TextField(default='', verbose_name='سوال / پرامپت کاربر'),
        ),
        migrations.AddField(
            model_name='smsgatewayconfig',
            name='provider_name',
            field=models.CharField(default='کاوه نگار / ملی پیامک واسط', max_length=100, verbose_name='نام سامانه پیامکی'),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='cost_deducted',
            field=models.IntegerField(default=240, verbose_name='هزینه کسرشده از کیف پول (تومان)'),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ کوئری'),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='model_used',
            field=models.CharField(max_length=150, verbose_name='مدل استفاده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='api_key',
            field=models.CharField(default='sk-or-v1-demo-key-anpk', max_length=255, verbose_name='کلید API سرویس هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='api_url',
            field=models.URLField(default='https://openrouter.ai/api/v1/chat/completions', verbose_name='آدرس API پرووایدر هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='default_model',
            field=models.CharField(default='google/gemini-2.5-flash', max_length=150, verbose_name='مدل هوش مصنوعی پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='wallet_rate_per_query',
            field=models.IntegerField(default=240, verbose_name='تعرفه کسر از کیف پول برای هر کوئری (تومان)'),
        ),
        migrations.AlterField(
            model_name='smsgatewayconfig',
            name='api_key',
            field=models.CharField(default='sms-gateway-demo-key-anpk', max_length=255, verbose_name='کلید API درگاه پیامک'),
        ),
        migrations.AlterField(
            model_name='smsgatewayconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='درگاه فعال است'),
        ),
        migrations.AlterField(
            model_name='smsgatewayconfig',
            name='sender_line',
            field=models.CharField(default='30005050', max_length=50, verbose_name='خط اختصاصی ارسال پیامک'),
        ),
    ]
