# Generated by Django 4.2.30 on 2026-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_ailog_options_alter_openrouterconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام نود / سرویس کلود')),
                ('status_label', models.CharField(default='آنلاین', max_length=50, verbose_name='وضعیت پایش (e.g. آنلاین، نگه\u200cداشت)')),
                ('uptime_percentage', models.CharField(default='۹۹.۹٪', max_length=20, verbose_name='درصد پایداری (Uptime)')),
                ('latency_ms', models.IntegerField(default=25, verbose_name='تخمین تاخیر شبکه (ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نود فعال است')),
            ],
            options={
                'verbose_name': 'نود کلود و وضعیت پایداری',
                'verbose_name_plural': 'پایش آنلاین نودها و سرویس\u200cها (Node Status)',
            },
        ),
    ]
