# Generated by Django 4.2.30 on 2026-08-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_clientcontractproject_options_and_more'),
        ('services', '0004_systemnodestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='projects.clientcontractproject', verbose_name='پروژه مرتبط'),
        ),
    ]
