# Generated by Django 4.2.30 on 2026-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی فرستنده')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
            },
        ),
    ]
