# Generated by Django 4.2.30 on 2026-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('author', models.CharField(default='تیم مهندسی ANPK', max_length=150, verbose_name='نویسنده')),
                ('summary', models.TextField(verbose_name='خلاصه مقاله')),
                ('content', models.TextField(verbose_name='متن کامل مقاله')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'مقاله مهندسی',
                'verbose_name_plural': 'مقالات و پایگاه دانش',
            },
        ),
    ]
