# Generated by Django 5.2.17 on 2026-08-12 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی مقاله')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات کوتاه')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='آیکون / تصویر دسته\u200cبندی')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو (Meta Title)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو (Meta Description)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقاله',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقالات وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان برچسب')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا برچسب')),
            ],
            options={
                'verbose_name': 'برچسب مقاله',
                'verbose_name_plural': 'برچسب\u200cهای مقالات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('author', models.CharField(default='دپارتمان مهندسی ANPK', max_length=150, verbose_name='نویسنده')),
                ('summary', models.TextField(verbose_name='خلاصه / چکیده مقاله')),
                ('content', models.TextField(verbose_name='متن کامل مقاله')),
                ('table_of_contents', models.BooleanField(default=True, verbose_name='نمایش فهرست مطالب')),
                ('read_time', models.CharField(default='۵ دقیقه', max_length=50, verbose_name='زمان تقریبی مطالعه')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='تصویر شاخص (Thumbnail)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='تصویر اصلی / هدر (Cover)')),
                ('views_count', models.IntegerField(default=0, verbose_name='تعداد بازدیدکنندگان')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('ARCHIVED', 'آرشیو شده')], default='PUBLISHED', max_length=20, verbose_name='وضعیت انتشار')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقاله ویژه / برگزیده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان انتشار (برای زمان\u200cبندی)')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ زمان\u200cبندی شده')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو (Meta Title)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو (Meta Description)')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان Open Graph (شبکه اجتماعی)')),
                ('og_description', models.TextField(blank=True, null=True, verbose_name='توضیحات Open Graph')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='articles/og/', verbose_name='تصویر Open Graph (1200x630)')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربية')], default='fa', max_length=5, verbose_name='زبان مقاله')),
                ('schema_type', models.CharField(choices=[('Article', 'مقاله'), ('NewsArticle', 'خبر'), ('BlogPosting', 'پست وبلاگ'), ('TechArticle', 'مقاله فنی'), ('HowTo', 'آموزش')], default='Article', max_length=30, verbose_name='نوع Schema.org')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='اجازه نظر دهی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.articlecategory', verbose_name='دسته\u200cبندی موضوعی مقاله')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.articletag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله مهندسی',
                'verbose_name_plural': 'مقالات و پایگاه دانش',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ارسالکننده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.articlecomment', verbose_name='پاسخ به')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات مقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
