# Generated by Django 4.2.30 on 2026-08-08 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله مهندسی', 'verbose_name_plural': 'مقالات و پایگاه دانش (Engineering Knowledge Base)'},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='مهندسی نرم\u200cافزار', max_length=150, verbose_name='دسته\u200cبندی موضوعی'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تصویر شاخص مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='مقاله ویژه / برگزیده'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.CharField(default='۵ دقیقه', max_length=50, verbose_name='زمان تقریبی مطالعه'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='سلامت دیجیتال, Microservices, جنگو', max_length=255, verbose_name='برچسب\u200cها (با کاما جدا کنید)'),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=340, verbose_name='تعداد بازدیدها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='دپارتمان مهندسی ANPK', max_length=150, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='متن کامل مقاله (Markdown/HTML)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='شناسه یکتا (slug)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(verbose_name='خلاصه / چکیده مقاله'),
        ),
    ]
