# Generated by Django 4.2.30 on 2026-08-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی مقاله')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا (slug)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات کوتاه')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقاله',
                'verbose_name_plural': '۱. دسته\u200cبندی\u200cهای مقالات وبلاگ (Blog Categories)',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله مهندسی', 'verbose_name_plural': '۲. مقالات و پایگاه دانش (Articles)'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.articlecategory', verbose_name='دسته\u200cبندی موضوعی مقاله'),
        ),
    ]
