# Generated by Django 4.2.30 on 2026-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlecategory_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله مهندسی', 'verbose_name_plural': 'مقالات و پایگاه دانش'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'دسته\u200cبندی مقاله', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقالات وبلاگ'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='متن کامل مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='شناسه یکتا'),
        ),
    ]
