# Generated by Django 4.2.30 on 2026-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدیدکنندگان'),
        ),
    ]
