# Generated by Django 4.2.30 on 2026-08-09 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان برچسب')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا برچسب')),
            ],
            options={
                'verbose_name': 'برچسب مقاله',
                'verbose_name_plural': 'برچسب\u200cهای مقالات',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='تصویر اصلی / هدر (Cover)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو (Meta Description)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو (Meta Title)'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان انتشار (برای زمان\u200cبندی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('ARCHIVED', 'آرشیو شده')], default='PUBLISHED', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='تصویر شاخص (Thumbnail)'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='آیکون / تصویر دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو (Meta Description)'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو (Meta Title)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه / برگزیده'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.articletag', verbose_name='برچسب\u200cها'),
        ),
    ]
