# Generated by Django 4.2.30 on 2026-08-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articletag_remove_article_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='اجازه نظر دهی'),
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربية')], default='fa', max_length=5, verbose_name='زبان مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات Open Graph'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/og/', verbose_name='تصویر Open Graph (1200x630)'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان Open Graph (شبکه اجتماعی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ زمان\u200cبندی شده'),
        ),
        migrations.AddField(
            model_name='article',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('NewsArticle', 'خبر'), ('BlogPosting', 'پست وبلاگ'), ('TechArticle', 'مقاله فنی'), ('HowTo', 'آموزش')], default='Article', max_length=30, verbose_name='نوع Schema.org'),
        ),
        migrations.AddField(
            model_name='article',
            name='table_of_contents',
            field=models.BooleanField(default=True, verbose_name='نمایش فهرست مطالب'),
        ),
    ]
