# Generated by Django 5.2.17 on 2026-08-15 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_organization_owner_user'),
        ('billing', '0001_initial'),
        ('portal', '0008_remove_clientmember_organization_and_more'),
        ('projects', '0002_alter_clientcontractproject_client'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نوتیفیکیشن')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization', verbose_name='سازمان / مشتری')),
            ],
            options={
                'verbose_name': 'اعلان داخل برنامه',
                'verbose_name_plural': 'اعلان\u200cهای داخل برنامه',
                'db_table': 'portal_inappnotification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLASupportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='پشتیبانی طلایی SLA ۲۴/۷', max_length=150, verbose_name='سطح قرارداد پشتیبانی')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع قرارداد')),
                ('duration_months', models.IntegerField(default=12, verbose_name='مدت قرارداد (ماه)')),
                ('support_schedule', models.CharField(default='24/7', max_length=50, verbose_name='ساعات پشتیبانی')),
                ('response_time_minutes', models.PositiveIntegerField(default=30, verbose_name='حداکثر زمان پاسخ اولیه (دقیقه)')),
                ('resolution_time_hours', models.PositiveIntegerField(default=4, verbose_name='حداکثر زمان رفع خطای بحرانی (ساعت)')),
                ('availability_percentage', models.DecimalField(decimal_places=2, default=99.9, max_digits=5, verbose_name='دسترس\u200cپذیری تضمین\u200cشده (درصد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='قرارداد فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سیستم')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_contracts', to='accounts.organization', verbose_name='سازمان / مشتری')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_contracts', to='projects.clientcontractproject', verbose_name='پروژه مرتبط')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_contract', to='billing.clientsubscription', verbose_name='اشتراک مرتبط')),
            ],
            options={
                'verbose_name': 'قرارداد پشتیبانی SLA',
                'verbose_name_plural': 'قراردادها و پشتیبانی SLA',
                'db_table': 'portal_slasupportcontract',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='نام ثبت\u200cکننده')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع تیکت پشتیبانی')),
                ('message', models.TextField(verbose_name='متن درخواست')),
                ('status', models.CharField(default='open', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تیکت')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.organization', verbose_name='سازمان / مشتری')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.clientcontractproject', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی مشتریان',
                'db_table': 'portal_supportticket',
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='پشتیبانی', max_length=255, verbose_name='نام فرستنده')),
                ('is_admin', models.BooleanField(default=True, verbose_name='آیا پاسخ از طرف ادمین است؟')),
                ('message', models.TextField(verbose_name='متن پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پاسخ')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.supportticket', verbose_name='تیکت مربوطه')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت',
                'db_table': 'portal_ticketreply',
            },
        ),
            ],
        ),
    ]
