# Generated by Django 4.2.30 on 2026-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام سازمان / بیمارستان')),
                ('contact_person', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی رابط')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('service_type', models.CharField(max_length=255, verbose_name='سرویس درخواستی')),
                ('budget_range', models.CharField(max_length=150, verbose_name='حدود بودجه')),
                ('timeline', models.CharField(max_length=150, verbose_name='زمان\u200cبندی مد نظر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('status', models.CharField(choices=[('new', 'جدید (نیازمند بررسی)'), ('contacted', 'در حال پیگیری و تماس'), ('contract', 'تایید و عقد قرارداد'), ('archived', 'بایگانی')], default='new', max_length=30, verbose_name='وضعیت پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
            ],
            options={
                'verbose_name': 'لید درخواست پروژه',
                'verbose_name_plural': 'لیدهای درخواست پروژه (فرم ۴ مرحله\u200cای)',
            },
        ),
    ]
