# Generated by Django 4.2.30 on 2026-08-08 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'یادداشت داخلی'), ('call', 'تماس تلفنی'), ('meeting', 'جلسه حضوری/آنلاین'), ('email', 'ایمیل/پیامک')], default='note', max_length=20, verbose_name='نوع فعالیت')),
                ('description', models.TextField(verbose_name='شرح فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.projectlead', verbose_name='لید مرتبط')),
            ],
            options={
                'verbose_name': 'سابقه فعالیت لید',
                'verbose_name_plural': 'سوابق فعالیت لیدها',
                'ordering': ['-created_at'],
            },
        ),
    ]
