# Generated by Django 4.2.30 on 2026-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='شرکت ارشیا نگین پردازش کویر', max_length=255)),
                ('tagline', models.CharField(default='طراح و مجری سامانه\u200cهای اختصاصی سازمانی', max_length=255)),
                ('phone', models.CharField(default='03534200000', max_length=50)),
                ('email', models.EmailField(default='info@anpk.ir', max_length=254)),
                ('address', models.TextField(default='ایران، استان یزد، شهرستان یزد، محله خرمشاه')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات پایه شرکت',
            },
        ),
        migrations.CreateModel(
            name='SystemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان شاخص')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار (مثلاً ۹۹.۹٪)')),
            ],
            options={
                'verbose_name': 'شاخص آمار',
                'verbose_name_plural': 'آمار کلان سیستم',
            },
        ),
    ]
