# Generated by Django 4.2.30 on 2026-08-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='پیشرو در توسعه پلتفرم\u200cهای سازمانی', max_length=255, verbose_name='متن بج بالایی هیرو')),
                ('main_title_static', models.CharField(default='معماری سامانه\u200cهای اختصاصی،', max_length=255, verbose_name='متن ثابت تیتر هیرو')),
                ('sub_description', models.TextField(default='شرکت «ارشیا نگین پردازش کویر» طراح و مجری سامانه\u200cهای مایکروپروسس بومی برای دانشگاه\u200cها، بیمارستان\u200cها و سازمان\u200cهای بزرگ کشور با پایداری ۹۹.۹٪ و ارائه مستندات کامل فنی.', verbose_name='توضیحات اصلی هیرو')),
                ('primary_button_text', models.CharField(default='ثبت درخواست پروژه (فرم ۴ مرحله\u200cای)', max_length=150, verbose_name='متن دکمه اصلی')),
                ('secondary_button_text', models.CharField(default='محصولات نرم\u200cافزاری', max_length=150, verbose_name='متن دکمه دوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='محتوای فعال هیرو')),
            ],
            options={
                'verbose_name': 'محتوای بخش هیرو',
                'verbose_name_plural': 'مدیریت بخش هیرو (صفحه اصلی)',
            },
        ),
        migrations.CreateModel(
            name='HeroTypewriterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='عبارت تایپ شونده')),
                ('color_class', models.CharField(default='gradient-text-primary', max_length=150, verbose_name='کلاس رنگ گرادیان')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typewriter_items', to='core.herosection', verbose_name='بخش هیرو')),
            ],
            options={
                'verbose_name': 'عبارت تایپ شونده هیرو',
                'verbose_name_plural': 'عبارات انیمیشنی هیرو',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SystemStat',
        ),
    ]
